# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SkyCatchFire' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  inhibit_all_warnings!

  pod 'Alamofire', '~> 4.8.0'
  pod 'RxSwift', '~> 5.1.0', :inhibit_warnings => true
  pod 'RxCocoa', '~> 5.1.0'
  pod 'RxDataSources', '~> 4.0'
  pod 'SwiftDate', '~> 6.0.3'
  pod 'RxGesture', '~> 3.0.2'
  pod 'SwiftLint', '~> 0.35.0'
  pod 'MVVM-C', :path => '../MVVM-C'
  pod 'JitsiMeetSDK', '~> 2.8.0'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
      end
    end
  end

  target 'SkyCatchFireTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SkyCatchFireUITests' do
    # Pods for testing
  end

end
