# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVM-C' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for MVVM-C
  pod 'Alamofire', '~> 4.8.0'
  pod 'RxSwift', '~> 5.1.0'
  pod 'RxCocoa', '~> 5.1.0'

  target 'MVVM-CTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVM-CUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
